name: Deploy Prometheus

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy on Hetzner
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_IP }}
          username: ${{ secrets.HETZNER_USERNAME }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            git clone git@github.com:smadixd/logging.git
            cd logging/prometheus
            sudo docker build -t my-prometheus .
            sudo docker stop my-prometheus || true
            sudo docker rm my-prometheus || true
            sudo docker run -d --name my-prometheus -p 9090:9090 my-prometheus
