global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["127.0.0.1:9090"]

  - job_name: "nginx"
    static_configs:
      - targets: ["my-nginx-exporter:9113"]

  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx_4xx_5xx]
    static_configs:
      - targets:
          - http://portfolio-container:5000
          - https://mohammadalsmadi.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: my-blackbox-exporter:9115

  - job_name: "fluentd"
    static_configs:
      - targets: ["my-fluentd:24231"]
