name: Deploy Grafana

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy on Hetzner
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_IP }}
          username: ${{ secrets.HETZNER_USERNAME }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            git clone git@github.com:smadixd/logging.git
            cd logging/grafana
            sudo docker build -t my-grafana .
            sudo docker stop my-grafana || true
            sudo docker rm my-grafana || true
            sudo docker run -d --name my-grafana -p 8080:8080 my-grafana
