name: Deploy Services

on:
  push:
    branches:
      - main

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy Grafana on Hetzner
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_IP }}
          username: ${{ secrets.HETZNER_USERNAME }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          port: ${{ secrets.HETZNER_PORT }}
          script: |
            git clone git@github.com:smadixd/logging.git || true
  deploy_grafana:
    runs-on: ubuntu-latest
    needs: clone
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy Grafana on Hetzner
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_IP }}
          username: ${{ secrets.HETZNER_USERNAME }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          port: ${{ secrets.HETZNER_PORT }}
          script: |
            cd logging/grafana
            sudo docker build -t my-grafana .
            sudo docker stop my-grafana || true
            sudo docker rm my-grafana || true
            sudo docker run -d --name my-grafana -p 127.0.0.1:8080:8080 -v grafana_data:/var/lib/grafana my-grafana
            sudo docker network connect my-network my-grafana || true

  deploy_prometheus:
    runs-on: ubuntu-latest
    needs: clone
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy Prometheus on Hetzner
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_IP }}
          username: ${{ secrets.HETZNER_USERNAME }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          port: ${{ secrets.HETZNER_PORT }}
          script: |
            cd logging/prometheus
            sudo docker build -t my-prometheus .
            sudo docker stop my-prometheus || true
            sudo docker rm my-prometheus || true
            sudo docker run -d --name my-prometheus -p 127.0.0.1:9090:9090 -v prometheus_data:/prometheus my-prometheus
            sudo docker network connect my-network my-prometheus || true

  deploy_nginx_exporter:
    runs-on: ubuntu-latest
    needs: clone
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy NGINX Exporter on Hetzner
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_IP }}
          username: ${{ secrets.HETZNER_USERNAME }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          port: ${{ secrets.HETZNER_PORT }}
          script: |
            cd logging/nginx-exporter
            sudo docker build -t my-nginx-exporter .
            sudo docker stop my-nginx-exporter || true
            sudo docker rm my-nginx-exporter || true
            sudo docker run -d --name my-nginx-exporter -p 9113:9113 my-nginx-exporter
            sudo docker network connect my-network my-nginx-exporter || true
