name: Deploy Services

on:
  push:
    branches:
      - main
    paths:
      - "logging/grafana/**"
      - "logging/prometheus/**"

jobs:
  deploy_grafana:
    if: contains(github.event.head_commit.message, 'grafana')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy Grafana on Hetzner
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_IP }}
          username: ${{ secrets.HETZNER_USERNAME }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            git clone git@github.com:smadixd/logging.git
            cd logging/grafana
            sudo docker build -t my-grafana .
            sudo docker stop my-grafana || true
            sudo docker rm my-grafana || true
            sudo docker run -d --name my-grafana -p 8080:8080 my-grafana
            sudo docker network connect my-network my-grafana || true

  deploy_prometheus:
    if: contains(github.event.head_commit.message, 'prometheus')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH and deploy Prometheus on Hetzner
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_IP }}
          username: ${{ secrets.HETZNER_USERNAME }}
          key: ${{ secrets.HETZNER_SSH_KEY }}
          script: |
            git clone git@github.com:smadixd/logging.git
            cd logging/prometheus
            sudo docker build -t my-prometheus .
            sudo docker stop my-prometheus || true
            sudo docker rm my-prometheus || true
            sudo docker run -d --name my-prometheus -p 9090:9090 my-prometheus
            sudo docker network connect my-network my-prometheus || true
